---
title: Jigsaw co
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jgswco@gmail.com
description: a multimedia design company with a focus on creating educational and entertaining VR experiences.
baseurl:
url: www.jigsawco.io
twitter_username: jekyllrb
github_username: jekyll
theme: minima
plugins:
- jekyll-feed
url: "http://jigsawco.io" # the hostname & protocol for site
plugins:
   - jekyll-sitemap
plugins:
   - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
